version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
    - "8080:3000"
    volumes: 
    - /usr/front/node_modules
    - .:/usr/front
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
    - /usr/front/node_modules
    - .:/usr/front
    command: ["npm", "run", "test"]
